		<input type="hidden" id="menu_id" name="menu_id" value="${menu_id}"/>
		<input type="hidden" id="searchBtnClickCount" name="searchBtnClickCount" value="${searchBtnClickCount}"/>
		<input type="hidden" id="tab0ClickCount" name="tab0ClickCount" value="0"/>
		<input type="hidden" id="tab1ClickCount" name="tab1ClickCount" value="0"/>
		<input type="hidden" id="tab2ClickCount" name="tab2ClickCount" value="0"/>
		<input type="hidden" id="tab3ClickCount" name="tab3ClickCount" value="0"/>
		<input type="hidden" id="tab4ClickCount" name="tab4ClickCount" value="0"/>
		<input type="hidden" id="tab5ClickCount" name="tab5ClickCount" value="0"/>
		<input type="hidden" id="tab6ClickCount" name="tab6ClickCount" value="0"/>
		<input type="hidden" id="tab7ClickCount" name="tab7ClickCount" value="0"/>
		<input type="hidden" id="tab8ClickCount" name="tab8ClickCount" value="0"/>
		<input type="hidden" id="tab9ClickCount" name="tab9ClickCount" value="0"/>
		<input type="hidden" id="tab10ClickCount" name="tab10ClickCount" value="0"/>
		<input type="hidden" id="tab11ClickCount" name="tab11ClickCount" value="0"/>
		<input type="hidden" id="tab12ClickCount" name="tab12ClickCount" value="0"/>
		<input type="hidden" id="tab13ClickCount" name="tab13ClickCount" value="0"/>
		<input type="hidden" id="tab14ClickCount" name="tab14ClickCount" value="0"/>
		<input type="hidden" id="tab15ClickCount" name="tab15ClickCount" value="0"/>
		<input type="hidden" id="tab16ClickCount" name="tab16ClickCount" value="0"/>
		<input type="hidden" id="tab17ClickCount" name="tab17ClickCount" value="0"/>
		<input type="hidden" id="tab18ClickCount" name="tab18ClickCount" value="0"/>
		<input type="hidden" id="tab19ClickCount" name="tab19ClickCount" value="0"/>
		<input type="hidden" id="tab20ClickCount" name="tab20ClickCount" value="0"/>
		<input type="hidden" id="tab21ClickCount" name="tab21ClickCount" value="0"/>
		<input type="hidden" id="tab22ClickCount" name="tab22ClickCount" value="0"/>
		<input type="hidden" id="call_from_parent" name="call_from_parent" value="${call_from_parent}"/>
		<input type="hidden" id="call_from_child" name="call_from_child" value="${call_from_child}"/>
		